/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface ContactInquiry {
  'id' : bigint,
  'status' : Status,
  'name' : string,
  'cityState' : string,
  'email' : string,
  'grade' : Grade,
  'message' : string,
  'timestamp' : Timestamp,
  'phone' : string,
  'preferredContactMethod' : ContactMethod,
  'whoIsFilling' : WhoIsFilling,
}
export type ContactMethod = { 'both' : null } |
  { 'email' : null } |
  { 'phone' : null };
export interface CounselingSessionBooking {
  'id' : bigint,
  'status' : Status,
  'preferredTimeWindow' : string,
  'name' : string,
  'cityState' : string,
  'email' : string,
  'grade' : Grade,
  'preferredDate' : string,
  'notes' : string,
  'preferredMode' : PreferredMode,
  'timestamp' : Timestamp,
  'phone' : string,
  'whoIsFilling' : WhoIsFilling,
}
export type Grade = { 'ten' : null } |
  { 'nine' : null } |
  { 'eight' : null };
export type PreferredMode = { 'in_person' : null } |
  { 'online' : null };
export interface PsychometricTestBooking {
  'id' : bigint,
  'status' : Status,
  'preferredTimeWindow' : string,
  'name' : string,
  'cityState' : string,
  'email' : string,
  'grade' : Grade,
  'preferredDate' : string,
  'notes' : string,
  'timestamp' : Timestamp,
  'phone' : string,
}
export type Status = { 'new' : null } |
  { 'closed' : null } |
  { 'reviewed' : null };
export type Timestamp = bigint;
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export type WhoIsFilling = { 'student' : null } |
  { 'parent' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'filterContactInquiriesByTimestamp' : ActorMethod<
    [Timestamp, Timestamp],
    Array<ContactInquiry>
  >,
  'filterCounselingSessionBookingsByTimestamp' : ActorMethod<
    [Timestamp, Timestamp],
    Array<CounselingSessionBooking>
  >,
  'filterPsychometricTestBookingsByTimestamp' : ActorMethod<
    [Timestamp, Timestamp],
    Array<PsychometricTestBooking>
  >,
  'getAllContactInquiries' : ActorMethod<[], Array<ContactInquiry>>,
  'getAllCounselingSessionBookings' : ActorMethod<
    [],
    Array<CounselingSessionBooking>
  >,
  'getAllPsychometricTestBookings' : ActorMethod<
    [],
    Array<PsychometricTestBooking>
  >,
  'getBookingsWithinDays' : ActorMethod<[bigint], bigint>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getContactInquiry' : ActorMethod<[bigint], ContactInquiry>,
  'getCounselingSessionBooking' : ActorMethod<
    [bigint],
    CounselingSessionBooking
  >,
  'getNewBookingsCount' : ActorMethod<[], bigint>,
  'getPsychometricTestBooking' : ActorMethod<[bigint], PsychometricTestBooking>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'submitContactInquiry' : ActorMethod<
    [
      string,
      WhoIsFilling,
      Grade,
      string,
      string,
      string,
      ContactMethod,
      string,
    ],
    bigint
  >,
  'submitCounselingSessionBooking' : ActorMethod<
    [
      string,
      WhoIsFilling,
      Grade,
      string,
      string,
      string,
      string,
      string,
      PreferredMode,
      string,
    ],
    bigint
  >,
  'submitPsychometricTestBooking' : ActorMethod<
    [string, Grade, string, string, string, string, string, string],
    bigint
  >,
  'updateStatus' : ActorMethod<[string, bigint, Status], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];