/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Timestamp = IDL.Nat;
export const Status = IDL.Variant({
  'new' : IDL.Null,
  'closed' : IDL.Null,
  'reviewed' : IDL.Null,
});
export const Grade = IDL.Variant({
  'ten' : IDL.Null,
  'nine' : IDL.Null,
  'eight' : IDL.Null,
});
export const ContactMethod = IDL.Variant({
  'both' : IDL.Null,
  'email' : IDL.Null,
  'phone' : IDL.Null,
});
export const WhoIsFilling = IDL.Variant({
  'student' : IDL.Null,
  'parent' : IDL.Null,
});
export const ContactInquiry = IDL.Record({
  'id' : IDL.Nat,
  'status' : Status,
  'name' : IDL.Text,
  'cityState' : IDL.Text,
  'email' : IDL.Text,
  'grade' : Grade,
  'message' : IDL.Text,
  'timestamp' : Timestamp,
  'phone' : IDL.Text,
  'preferredContactMethod' : ContactMethod,
  'whoIsFilling' : WhoIsFilling,
});
export const PreferredMode = IDL.Variant({
  'in_person' : IDL.Null,
  'online' : IDL.Null,
});
export const CounselingSessionBooking = IDL.Record({
  'id' : IDL.Nat,
  'status' : Status,
  'preferredTimeWindow' : IDL.Text,
  'name' : IDL.Text,
  'cityState' : IDL.Text,
  'email' : IDL.Text,
  'grade' : Grade,
  'preferredDate' : IDL.Text,
  'notes' : IDL.Text,
  'preferredMode' : PreferredMode,
  'timestamp' : Timestamp,
  'phone' : IDL.Text,
  'whoIsFilling' : WhoIsFilling,
});
export const PsychometricTestBooking = IDL.Record({
  'id' : IDL.Nat,
  'status' : Status,
  'preferredTimeWindow' : IDL.Text,
  'name' : IDL.Text,
  'cityState' : IDL.Text,
  'email' : IDL.Text,
  'grade' : Grade,
  'preferredDate' : IDL.Text,
  'notes' : IDL.Text,
  'timestamp' : Timestamp,
  'phone' : IDL.Text,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'filterContactInquiriesByTimestamp' : IDL.Func(
      [Timestamp, Timestamp],
      [IDL.Vec(ContactInquiry)],
      ['query'],
    ),
  'filterCounselingSessionBookingsByTimestamp' : IDL.Func(
      [Timestamp, Timestamp],
      [IDL.Vec(CounselingSessionBooking)],
      ['query'],
    ),
  'filterPsychometricTestBookingsByTimestamp' : IDL.Func(
      [Timestamp, Timestamp],
      [IDL.Vec(PsychometricTestBooking)],
      ['query'],
    ),
  'getAllContactInquiries' : IDL.Func([], [IDL.Vec(ContactInquiry)], ['query']),
  'getAllCounselingSessionBookings' : IDL.Func(
      [],
      [IDL.Vec(CounselingSessionBooking)],
      ['query'],
    ),
  'getAllPsychometricTestBookings' : IDL.Func(
      [],
      [IDL.Vec(PsychometricTestBooking)],
      ['query'],
    ),
  'getBookingsWithinDays' : IDL.Func([IDL.Nat], [IDL.Nat], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getContactInquiry' : IDL.Func([IDL.Nat], [ContactInquiry], ['query']),
  'getCounselingSessionBooking' : IDL.Func(
      [IDL.Nat],
      [CounselingSessionBooking],
      ['query'],
    ),
  'getNewBookingsCount' : IDL.Func([], [IDL.Nat], ['query']),
  'getPsychometricTestBooking' : IDL.Func(
      [IDL.Nat],
      [PsychometricTestBooking],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'submitContactInquiry' : IDL.Func(
      [
        IDL.Text,
        WhoIsFilling,
        Grade,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        ContactMethod,
        IDL.Text,
      ],
      [IDL.Nat],
      [],
    ),
  'submitCounselingSessionBooking' : IDL.Func(
      [
        IDL.Text,
        WhoIsFilling,
        Grade,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        PreferredMode,
        IDL.Text,
      ],
      [IDL.Nat],
      [],
    ),
  'submitPsychometricTestBooking' : IDL.Func(
      [
        IDL.Text,
        Grade,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
      ],
      [IDL.Nat],
      [],
    ),
  'updateStatus' : IDL.Func([IDL.Text, IDL.Nat, Status], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Timestamp = IDL.Nat;
  const Status = IDL.Variant({
    'new' : IDL.Null,
    'closed' : IDL.Null,
    'reviewed' : IDL.Null,
  });
  const Grade = IDL.Variant({
    'ten' : IDL.Null,
    'nine' : IDL.Null,
    'eight' : IDL.Null,
  });
  const ContactMethod = IDL.Variant({
    'both' : IDL.Null,
    'email' : IDL.Null,
    'phone' : IDL.Null,
  });
  const WhoIsFilling = IDL.Variant({
    'student' : IDL.Null,
    'parent' : IDL.Null,
  });
  const ContactInquiry = IDL.Record({
    'id' : IDL.Nat,
    'status' : Status,
    'name' : IDL.Text,
    'cityState' : IDL.Text,
    'email' : IDL.Text,
    'grade' : Grade,
    'message' : IDL.Text,
    'timestamp' : Timestamp,
    'phone' : IDL.Text,
    'preferredContactMethod' : ContactMethod,
    'whoIsFilling' : WhoIsFilling,
  });
  const PreferredMode = IDL.Variant({
    'in_person' : IDL.Null,
    'online' : IDL.Null,
  });
  const CounselingSessionBooking = IDL.Record({
    'id' : IDL.Nat,
    'status' : Status,
    'preferredTimeWindow' : IDL.Text,
    'name' : IDL.Text,
    'cityState' : IDL.Text,
    'email' : IDL.Text,
    'grade' : Grade,
    'preferredDate' : IDL.Text,
    'notes' : IDL.Text,
    'preferredMode' : PreferredMode,
    'timestamp' : Timestamp,
    'phone' : IDL.Text,
    'whoIsFilling' : WhoIsFilling,
  });
  const PsychometricTestBooking = IDL.Record({
    'id' : IDL.Nat,
    'status' : Status,
    'preferredTimeWindow' : IDL.Text,
    'name' : IDL.Text,
    'cityState' : IDL.Text,
    'email' : IDL.Text,
    'grade' : Grade,
    'preferredDate' : IDL.Text,
    'notes' : IDL.Text,
    'timestamp' : Timestamp,
    'phone' : IDL.Text,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'filterContactInquiriesByTimestamp' : IDL.Func(
        [Timestamp, Timestamp],
        [IDL.Vec(ContactInquiry)],
        ['query'],
      ),
    'filterCounselingSessionBookingsByTimestamp' : IDL.Func(
        [Timestamp, Timestamp],
        [IDL.Vec(CounselingSessionBooking)],
        ['query'],
      ),
    'filterPsychometricTestBookingsByTimestamp' : IDL.Func(
        [Timestamp, Timestamp],
        [IDL.Vec(PsychometricTestBooking)],
        ['query'],
      ),
    'getAllContactInquiries' : IDL.Func(
        [],
        [IDL.Vec(ContactInquiry)],
        ['query'],
      ),
    'getAllCounselingSessionBookings' : IDL.Func(
        [],
        [IDL.Vec(CounselingSessionBooking)],
        ['query'],
      ),
    'getAllPsychometricTestBookings' : IDL.Func(
        [],
        [IDL.Vec(PsychometricTestBooking)],
        ['query'],
      ),
    'getBookingsWithinDays' : IDL.Func([IDL.Nat], [IDL.Nat], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getContactInquiry' : IDL.Func([IDL.Nat], [ContactInquiry], ['query']),
    'getCounselingSessionBooking' : IDL.Func(
        [IDL.Nat],
        [CounselingSessionBooking],
        ['query'],
      ),
    'getNewBookingsCount' : IDL.Func([], [IDL.Nat], ['query']),
    'getPsychometricTestBooking' : IDL.Func(
        [IDL.Nat],
        [PsychometricTestBooking],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'submitContactInquiry' : IDL.Func(
        [
          IDL.Text,
          WhoIsFilling,
          Grade,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          ContactMethod,
          IDL.Text,
        ],
        [IDL.Nat],
        [],
      ),
    'submitCounselingSessionBooking' : IDL.Func(
        [
          IDL.Text,
          WhoIsFilling,
          Grade,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          PreferredMode,
          IDL.Text,
        ],
        [IDL.Nat],
        [],
      ),
    'submitPsychometricTestBooking' : IDL.Func(
        [
          IDL.Text,
          Grade,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
        ],
        [IDL.Nat],
        [],
      ),
    'updateStatus' : IDL.Func([IDL.Text, IDL.Nat, Status], [], []),
  });
};

export const init = ({ IDL }) => { return []; };